spring.application.name=ratelimiter
# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://pg-3100be88-luvprits33-4bc9.a.aivencloud.com:20675/defaultdb?ssl=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_xa-H8cU627lHY9Qt28P

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092